# Setup
title:               Onur Özdemir
tagline:             'Find experience and portfolio of Onur Özdemir'
description:         ''
url:                 http://oozd.github.io
baseurl:             ''
paginate:            5
permalink:           :title.html

# About/contact
author:
  name:              Onur Özdemir
  email:             oozdemironur@gmail.com

# Custom vars
version:             1.1.0
